on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deps
      run: |
        set -ex
        if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
        go get github.com/axw/gocov/gocov
        go get github.com/modocache/gover
        go get github.com/mattn/goveralls
    - name: Install
      run: |
        set -ex
        go get -t -v . ./pry ./generate ./playground/server
    - name: Test
      run: |
        set -ex
        go test -v -race -coverprofile=pry.coverprofile ./pry
        go test -v -race -coverprofile=generate.coverprofile ./generate
        go test -v -race -coverprofile=main.coverprofile
        go test -v -race -coverprofile=server.coverprofile ./playground/server
        $HOME/gopath/bin/gover
        $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=gover.coverprofile
